{
  "questionText": "Как могут обрабатываться  ошибки при состоянии промиса `reject`?",
  "type": "checkbox",
  "answers": [
    {
      "text": "С помощью метода `.catch`",
      "isCorrect": true
    },
    {
      "text": "С помощью метода `.finally`",
      "isCorrect": false
    },
    {
      "text": "Промис переходит в состояние `reject` в случае успешного выполнения, при котором не требуется обработка ошибок",
      "isCorrect": false
    },
    {
      "text": "С помощью второго аргумента следующего метода `.then`",
      "isCorrect": true
    }
  ],
  "descriptionMarkup": "Чаще всего для обработки ошибок используют метод `.catch`, но будет не лишним знать, что метод `.then` на самом деле принимает два аргумента.\n\nВторым аргументом является функция, которая выполняется, когда промис переходит в состояние «выполнен с ошибкой» (`reject`) и получает ошибку."
}
